Use resource name + restore all desktops + sanitize restore
bainonline/fullscreen-to-new-desktop pull request #4
Opened 2024-03-25 08:31 UTC by Ubiquitine

- Use application/resource name for new desktop
- Restore all desktops the window was before maximize
- Sanitize restored desktops, e.g. when desktop was deleted in between.

I know, those are a lot of changes in a single PR...  
Using window's resource name for new desktop just looks better (kinda imitate OSX).
The rest is just improved behavior for storing and restoring window's desktops.

2024-03-28 18:49 UTC, bainonline-acpr requested changes

2024-03-28 18:49 UTC, bainonline-acpr commented on contents/code/main.js
> +    log("Creating new desktop with name : " | window.resourceName.toString());
I know this looks better... but when i have two or more firefox windows (or don't even talk about chrome) this doesn't always work.
ResourceName is not really guaranteed to be unique, we can't really use it here.
I am open to ideas,
One is if we can add uuid to some other desktop property  and set the name to resource name.
And use that other property to search the app<-> desktop association.

2024-03-28 18:49 UTC, bainonline-acpr commented
Except for #1  
Rest is all good, can you split the PR? so that #2 and #3 can go in?

2024-03-28 19:01 UTC, bainonline commented on contents/code/main.js
> +    log("Creating new desktop with name : " | window.resourceName.toString());
Another idea is to keep the desktop ID <-> app mapping in our own in memory array, and not rely on desktop name for matching it with our window. (Will require etxra work) 
This will add to the memory usage of the script. Also need to worry about leaks.

2024-03-29 04:16 UTC, Ubiquitine commented
Ok. I created a new PR.

2024-03-29 04:17 UTC, closed without merging